// Code generated by mockery 2.9.0. DO NOT EDIT.

package initializer

import mock "github.com/stretchr/testify/mock"

// MockInitializer is an autogenerated mock type for the Initializer type
type MockInitializer struct {
	mock.Mock
}

// Initialize provides a mock function with given fields:
func (_m *MockInitializer) Initialize() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
