// Code generated by mockery 2.9.0. DO NOT EDIT.

package state

import mock "github.com/stretchr/testify/mock"

// MockPersistence is an autogenerated mock type for the Persistence type
type MockPersistence struct {
	mock.Mock
}

// Load provides a mock function with given fields:
func (_m *MockPersistence) Load() (SerializedState, error) {
	ret := _m.Called()

	var r0 SerializedState
	if rf, ok := ret.Get(0).(func() SerializedState); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SerializedState)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: state
func (_m *MockPersistence) Save(state SerializedState) error {
	ret := _m.Called(state)

	var r0 error
	if rf, ok := ret.Get(0).(func(SerializedState) error); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
