// Code generated by mockery 2.9.0. DO NOT EDIT.

package serviceaccount

import mock "github.com/stretchr/testify/mock"

// MockSecretProvider is an autogenerated mock type for the SecretProvider type
type MockSecretProvider struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *MockSecretProvider) Get() (*Secret, error) {
	ret := _m.Called()

	var r0 *Secret
	if rf, ok := ret.Get(0).(func() *Secret); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Secret)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
