// Code generated by mockery 2.9.0. DO NOT EDIT.

package k8s

import mock "github.com/stretchr/testify/mock"

// MockPodIndexProvider is an autogenerated mock type for the PodIndexProvider type
type MockPodIndexProvider struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *MockPodIndexProvider) Get() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
