// Code generated by mockery 2.9.0. DO NOT EDIT.

package k8s

import mock "github.com/stretchr/testify/mock"

// MockSecret is an autogenerated mock type for the Secret type
type MockSecret struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *MockSecret) Get() (map[string][]byte, error) {
	ret := _m.Called()

	var r0 map[string][]byte
	if rf, ok := ret.Get(0).(func() map[string][]byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Put provides a mock function with given fields: _a0
func (_m *MockSecret) Put(_a0 map[string][]byte) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string][]byte) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
