// Code generated by mockery 2.9.0. DO NOT EDIT.

package ssm

import (
	request "github.com/aws/aws-sdk-go/aws/request"
	mock "github.com/stretchr/testify/mock"
)

// MockAWSRequester is an autogenerated mock type for the AWSRequester type
type MockAWSRequester struct {
	mock.Mock
}

// NewRequest provides a mock function with given fields: operation, params, data
func (_m *MockAWSRequester) NewRequest(operation *request.Operation, params interface{}, data interface{}) AWSRequest {
	ret := _m.Called(operation, params, data)

	var r0 AWSRequest
	if rf, ok := ret.Get(0).(func(*request.Operation, interface{}, interface{}) AWSRequest); ok {
		r0 = rf(operation, params, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(AWSRequest)
		}
	}

	return r0
}
