// Code generated by mockery 2.9.0. DO NOT EDIT.

package ssm

import mock "github.com/stretchr/testify/mock"

// MockAWSRequest is an autogenerated mock type for the AWSRequest type
type MockAWSRequest struct {
	mock.Mock
}

// Send provides a mock function with given fields:
func (_m *MockAWSRequest) Send() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
