// Code generated by mockery 2.9.0. DO NOT EDIT.

package agent

import (
	state "github.com/aws/amazon-eks-connector/pkg/state"
	mock "github.com/stretchr/testify/mock"
)

// MockRegistration is an autogenerated mock type for the Registration type
type MockRegistration struct {
	mock.Mock
}

// Register provides a mock function with given fields:
func (_m *MockRegistration) Register() (*state.State, error) {
	ret := _m.Called()

	var r0 *state.State
	if rf, ok := ret.Get(0).(func() *state.State); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*state.State)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
